/**
 * @file dsp_identity.h
 * @brief DSP Embedded device identity – X.509 certificate provisioning.
 *
 * Loads the DER-encoded device certificate and ECDSA private key that are
 * embedded into the firmware image via idf_component_register(EMBED_FILES).
 *
 * In production each device carries a unique certificate issued by the
 * deployment CA; the embedded files are replaced at provisioning time.
 * During development the placeholder files generated by
 * tools/gen_dev_certs.sh are used.
 *
 * Typical usage (integrates with dsp_tls, DSP-101):
 *   dsp_identity_init();
 *   dsp_tls_server_init(&tls_ctx,
 *       dsp_identity_get_cert(&cert_len), cert_len,
 *       dsp_identity_get_key(&key_len),   key_len,
 *       "dsp_tls");
 *
 * Used by: main (DSP-201), dsp_tls (DSP-101)
 */

#pragma once

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initialise the identity module.
 *
 * Validates that the embedded certificate and key are non-empty.
 * On ESP_PLATFORM: parses the X.509 certificate with mbedTLS and logs
 * the subject CN and validity period.
 *
 * @return ESP_OK on success.
 *         ESP_ERR_INVALID_STATE if cert or key data is missing/empty.
 *         ESP_ERR_INVALID_ARG   if DER parsing fails (malformed cert).
 */
esp_err_t dsp_identity_init(void);

/**
 * @brief Release resources held by the identity module.
 *
 * On ESP_PLATFORM: frees the mbedTLS x509_crt object parsed at init.
 * Safe to call without a preceding init.
 */
void dsp_identity_deinit(void);

/**
 * @brief Return a pointer to the embedded DER-encoded device certificate.
 *
 * The pointer is valid for the lifetime of the firmware; no copy is made.
 *
 * @param[out] out_len  Populated with the byte length of the certificate.
 *                      Must not be NULL.
 * @return Pointer to DER data, or NULL if not provisioned.
 */
const uint8_t *dsp_identity_get_cert(size_t *out_len);

/**
 * @brief Return a pointer to the embedded DER-encoded private key.
 *
 * @param[out] out_len  Populated with the byte length of the key.
 *                      Must not be NULL.
 * @return Pointer to DER data, or NULL if not provisioned.
 */
const uint8_t *dsp_identity_get_key(size_t *out_len);

/**
 * @brief Returns true if init succeeded and cert+key are present.
 */
bool dsp_identity_is_provisioned(void);

#ifdef __cplusplus
}
#endif
